// Generated by tools/make_art.py - do not edit
#ifndef GFX_DATA_H
#define GFX_DATA_H
#include <stdint.h>

#define SPR_DOWN0 0
#define SPR_DOWN1 2
#define SPR_UP0 4
#define SPR_UP1 6
#define SPR_LEFT0 8
#define SPR_LEFT1 10
#define SPR_SPIN 12
#define SPR_RIGHT0 14
#define SPR_RIGHT1 16
#define SPR_FLASK 18
#define SPR_SHADOW 20
#define SPR_OPPIE 22
#define SPR_TILE_COUNT 24
#define BG_BASE 24
#define T_FLOOR 24
#define T_STAR 25
#define T_OPPIE 26
#define T_OPPIE_HAPPY 27
#define T_OPPIE_LOOK_L 28
#define T_OPPIE_LOOK_U 29
#define T_OPPIE_LOOK_D 30
#define T_OPPIE_STUN 31
#define T_APPEAR0 32
#define T_APPEAR1 33
#define T_APPEAR2 34
#define T_MUSH 35
#define T_MUSH_APPEAR 36
#define T_BRICK 37
#define T_BRICK_BOTTOM 38
#define T_WINDOW 39
#define T_PANEL 40
#define T_PANEL_EDGE_L 41
#define T_PANEL_EDGE_R 42
#define T_DOT_OFF 43
#define T_DOT_ON 44
#define T_BLACK 45
#define T_GRASS 46
#define T_TREE0 47
#define T_TREE1 48
#define T_TREE2 49
#define T_TREE3 50
#define T_CAT0 51
#define T_CAT1 52
#define T_CAT2 53
#define T_CAT3 54
#define T_CAT4 55
#define T_CAT5 56
#define T_WITCH0 57
#define T_WITCH1 58
#define T_WITCH2 59
#define T_WITCH3 60
#define T_WITCH4 61
#define T_WITCH5 62
#define T_VINE_H 63
#define T_VINE_H2 64
#define T_VINE_V 65
#define T_FLOWER 66
#define T_VINE_CORNER 67
#define T_FONT_48 68
#define T_FONT_49 69
#define T_FONT_50 70
#define T_FONT_51 71
#define T_FONT_52 72
#define T_FONT_53 73
#define T_FONT_54 74
#define T_FONT_55 75
#define T_FONT_56 76
#define T_FONT_57 77
#define T_FONT_65 78
#define T_FONT_66 79
#define T_FONT_67 80
#define T_FONT_68 81
#define T_FONT_69 82
#define T_FONT_70 83
#define T_FONT_71 84
#define T_FONT_72 85
#define T_FONT_73 86
#define T_FONT_74 87
#define T_FONT_75 88
#define T_FONT_76 89
#define T_FONT_77 90
#define T_FONT_78 91
#define T_FONT_79 92
#define T_FONT_80 93
#define T_FONT_81 94
#define T_FONT_82 95
#define T_FONT_83 96
#define T_FONT_84 97
#define T_FONT_85 98
#define T_FONT_86 99
#define T_FONT_87 100
#define T_FONT_88 101
#define T_FONT_89 102
#define T_FONT_90 103
#define T_FONT_45 104
#define T_FONT_33 105
#define T_FONT_46 106
#define T_FONT_39 107
#define T_FONT_44 108
#define T_FONT_120 109
#define T_FONT_32 110
#define T_FONT_64 111
#define T_BIG_M0 112
#define T_BIG_M1 113
#define T_BIG_M2 114
#define T_BIG_M3 115
#define T_BIG_A0 116
#define T_BIG_A1 117
#define T_BIG_A2 118
#define T_BIG_A3 119
#define T_BIG_G0 120
#define T_BIG_G1 121
#define T_BIG_G2 122
#define T_BIG_G3 123
#define T_BIG_I0 124
#define T_BIG_I1 125
#define T_BIG_I2 126
#define T_BIG_I3 127
#define T_BIG_C0 128
#define T_BIG_C1 129
#define T_BIG_C2 130
#define T_BIG_C3 131
#define T_BIG_R0 132
#define T_BIG_R1 133
#define T_BIG_R2 134
#define T_BIG_R3 135
#define T_BIG_D0 136
#define T_BIG_D1 137
#define T_BIG_D2 138
#define T_BIG_D3 139
#define T_BIG_E0 140
#define T_BIG_E1 141
#define T_BIG_E2 142
#define T_BIG_E3 143
#define T_BIG_N0 144
#define T_BIG_N1 145
#define T_BIG_N2 146
#define T_BIG_N3 147
#define BG_TILE_COUNT 124
#define FONT_FIRST 68
#define BIG_FIRST 112
#define FONT_ORDER "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-!.',x @"

extern const uint8_t spr_tiles[];
extern const uint8_t bg_tiles[];
extern const uint8_t frame_map[20*18];
extern const uint8_t frame_attr[20*18];
extern const uint8_t title_map[20*18];
extern const uint8_t title_attr[20*18];

#endif
