// Generated by tools/make_art.py - do not edit
#ifndef GFX_DATA_H
#define GFX_DATA_H
#include <stdint.h>

#define SPR_DOWN0 0
#define SPR_DOWN1 2
#define SPR_UP0 4
#define SPR_UP1 6
#define SPR_LEFT0 8
#define SPR_LEFT1 10
#define SPR_SPIN 12
#define SPR_RIGHT0 14
#define SPR_RIGHT1 16
#define SPR_FLASK 18
#define SPR_SHADOW 20
#define SPR_TILE_COUNT 22
#define BG_BASE 22
#define T_FLOOR 22
#define T_STAR 23
#define T_OPPIE 24
#define T_OPPIE_HAPPY 25
#define T_OPPIE_LOOK_L 26
#define T_OPPIE_LOOK_U 27
#define T_OPPIE_LOOK_D 28
#define T_OPPIE_STUN 29
#define T_APPEAR0 30
#define T_APPEAR1 31
#define T_APPEAR2 32
#define T_MUSH 33
#define T_MUSH_APPEAR 34
#define T_BRICK 35
#define T_BRICK_BOTTOM 36
#define T_WINDOW 37
#define T_PANEL 38
#define T_PANEL_EDGE_L 39
#define T_PANEL_EDGE_R 40
#define T_DOT_OFF 41
#define T_DOT_ON 42
#define T_BLACK 43
#define T_GRASS 44
#define T_TREE0 45
#define T_TREE1 46
#define T_TREE2 47
#define T_TREE3 48
#define T_CAT0 49
#define T_CAT1 50
#define T_CAT2 51
#define T_CAT3 52
#define T_CAT4 53
#define T_CAT5 54
#define T_WITCH0 55
#define T_WITCH1 56
#define T_WITCH2 57
#define T_WITCH3 58
#define T_WITCH4 59
#define T_WITCH5 60
#define T_FONT_48 61
#define T_FONT_49 62
#define T_FONT_50 63
#define T_FONT_51 64
#define T_FONT_52 65
#define T_FONT_53 66
#define T_FONT_54 67
#define T_FONT_55 68
#define T_FONT_56 69
#define T_FONT_57 70
#define T_FONT_65 71
#define T_FONT_66 72
#define T_FONT_67 73
#define T_FONT_68 74
#define T_FONT_69 75
#define T_FONT_70 76
#define T_FONT_71 77
#define T_FONT_72 78
#define T_FONT_73 79
#define T_FONT_74 80
#define T_FONT_75 81
#define T_FONT_76 82
#define T_FONT_77 83
#define T_FONT_78 84
#define T_FONT_79 85
#define T_FONT_80 86
#define T_FONT_81 87
#define T_FONT_82 88
#define T_FONT_83 89
#define T_FONT_84 90
#define T_FONT_85 91
#define T_FONT_86 92
#define T_FONT_87 93
#define T_FONT_88 94
#define T_FONT_89 95
#define T_FONT_90 96
#define T_FONT_45 97
#define T_FONT_33 98
#define T_FONT_46 99
#define T_FONT_39 100
#define T_FONT_44 101
#define T_FONT_120 102
#define T_FONT_32 103
#define BG_TILE_COUNT 82
#define FONT_FIRST 61
#define FONT_ORDER "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-!.',x "

extern const uint8_t spr_tiles[];
extern const uint8_t bg_tiles[];
extern const uint8_t frame_map[20*18];
extern const uint8_t frame_attr[20*18];

#endif
