/* generated by tools/sfx_tables.py - do not edit */
#ifndef SFX_TABLES_H
#define SFX_TABLES_H
#include <stdint.h>
typedef struct { uint16_t x; uint8_t env; } sfx_step_t;   /* env: NR22 with a retrigger, 0 = glide */
typedef struct { uint8_t duty; uint8_t len; const sfx_step_t *steps; } sfx_prog_t;
enum { SFX_PICKUP_A, SFX_PICKUP_B, SFX_PICKUP_C, SFX_PICKUP_D, SFX_JUMP, SFX_POWERUP, SFX_EAT, SFX_TICK };
extern const sfx_prog_t sfx_progs[];
#endif
