#!/usr/bin/env python3
"""Per-frame sound effects on channel 2, written as editable lists -> src/sfx_tables.c + include/sfx_tables.h.
Never edit the generated files by hand; change the lists here and rerun.

An effect is a pulse duty (12, 25, 50 or 75 %) and one entry per frame (60 a second). An entry is a pitch in Hz,
or (Hz, 'vV') / (Hz, 'vV+P') / (Hz, 'vV-P'): retrigger the note at volume V (0-15) with the hardware envelope
rising or falling one step every P/64 s (no sign: constant volume). The first entry must retrigger. After the
last entry the note keeps its pitch and envelope, so every effect ends on a fall ('-1' is the fastest, about a
step a frame): cutting the channel instead drops the pulse's DC level at once and thumps. Pitches between
retriggers glide without restarting the note.

The pitches and levels were measured frame by frame from the original's effects (tools/sfx_page.py lists the
events): the collect/jump sounds are short pitch glides, the power-up is a wind-up followed by rising whoops; the eat sound is a downward gulp with an echo; the power
warning is a triple beep. The beeps' gaps are a 'v0' retrigger on a 12.5 % pulse, whose small DC step does not thump.

usage: sfx_tables.py
"""
import os, re

EFFECTS = {
    # sfx_collect05a-d: a soft square sliding up about a fourth; the game picks one of the four at random
    'pickup_a': (50, [(197, 'v8'), (205, 'v11'), 215, 226, 237, 237, 248, (254, 'v8-1'), 258]),
    'pickup_b': (50, [(230, 'v8'), (237, 'v11'), 248, 248, 280, 291, 302, (312, 'v8-1'), 317]),
    'pickup_c': (50, [(275, 'v8'), (276, 'v11'), 280, 296, 312, 334, 345, (360, 'v8-1'), 364]),
    'pickup_d': (50, [(310, 'v8'), (321, 'v11'), 345, 373, 403, 437, 444, (485, 'v8-1'), 487]),
    # sfx_jump03: C5 up to F5 in 8 frames, swelling for 3 frames and dying away
    'jump': (25, [(517, 'v6+1'), 519, 555, (592, 'v11-1'), 635, (638, 'v7-1'), (687, 'v4-1'), 695]),
    # sfx_special02: a wobbling wind-up from D3, then whoops an octave or more wide, each starting higher and quieter
    'powerup': (25, [
        (151, 'v6+1'), 161, 169, 172, 176,
        (161, 'v14'), 167, 172, 183, 183, 183, 183, 201, 215, 226, 233,
        (205, 'v14'), 215, 226, 248, 255, 258,
        (232, 'v13'), 248, 251, 255, 291, 312,
        (250, 'v9'), 251, 251, 291, 304, 334, 370, 398,
        (276, 'v9'), 291, 301, 326, 355, 388, 424, 477,
        (334, 'v7'), 345, 371, 404, 495, 495, 495, 587,
        (377, 'v5'), 388, 420, 510, 510, 511, 592, 671, 786,
        (398, 'v4'), 474, 474, 474, 581, 660, 886, 888, 888,
        (485, 'v3'), 488, 488, 576, 646, 728, 980, 980, 980,
        (506, 'v3'), 506, 506, 571, 630, 700, 904, 904, 904, 1260, 1572,
        (524, 'v2'), 610, 611, 675, 746, 947, 947, 947, 1227, 1491, 1491,
        (757, 'v2'), 754, 931, 931, 931, 1202, 1414, 1723, 1723, 1723, (1723, 'v2-1')]),
    # sfx_die00 (eating an enemy): a bright blip dropping into a low square that steps down E3 -> C#3 -> A#2,
    # then a faint echo of the drop
    'eat': (50, [
        (980, 'v12'), 600, (172, 'v15'), 165, 161, 150, 140, 138, 118, 118, 116, (113, 'v8-1'), 110,
        (172, 'v3'), 165, 161, 150, 140, (138, 'v2-1'), 118]),
    # sfx_select06 (150/100/50 frames of power left): three short high beeps near A6, each quieter
    'tick': (12, [
        (1750, 'v13-1'), 1750, 1750, (1750, 'v0'), 1750,
        (1750, 'v11-1'), 1750, 1750, (1750, 'v0'), 1750, 1750,
        (1750, 'v7-1'), 1750, 1750, (1750, 'v0')]),
}
DUTY = {12: 0x00, 25: 0x40, 50: 0x80, 75: 0xC0}
# Every volume above is scaled by GAIN so the effects sit under the melody: the lead (CH1) is a 12.5 % pulse at 15,
# RMS ~0.33 x 15 = 5; a 50 % pickup at 11 was 0.5 x 11 = 5.5, louder than the tune. 0.7 is -3 dB.
GAIN = 0.7

def gb_x(hz):
    x = round(2048 - 131072 / hz)
    assert 0 <= x < 2048, hz
    return x

def env(code):
    m = re.fullmatch(r'v(\d+)(?:([+-])(\d))?', code)
    assert m, code
    v = int(m[1]); assert 0 <= v <= 15, code
    v = max(1, round(v * GAIN)) if v else 0
    pace = int(m[3] or 0); up = m[2] == '+'
    e = (v << 4) | (0x08 if up else 0) | pace
    return e if e else 0x08            # NR22 = 0 would switch the DAC off; 0x08 is silent but keeps it on

def build():
    names = list(EFFECTS)
    c = ['/* generated by tools/sfx_tables.py - do not edit */', '#pragma bank 1', '#include "sfx_tables.h"', '']
    for n in names:
        duty, steps = EFFECTS[n]
        assert isinstance(steps[0], tuple), n + ': the first frame must retrigger'
        assert len(steps) < 256, n
        rows = []
        for s in steps:
            hz, e = (s[0], env(s[1])) if isinstance(s, tuple) else (s, 0)
            rows.append('{%d,0x%02X}' % (gb_x(hz), e))
        c.append('static const sfx_step_t %s_steps[] = {' % n)
        for i in range(0, len(rows), 10): c.append('    ' + ', '.join(rows[i:i + 10]) + ',')
        c.append('};')
    c.append('const sfx_prog_t sfx_progs[] = {')
    for n in names:
        duty, steps = EFFECTS[n]
        c.append('    {0x%02X, %d, %s_steps},' % (DUTY[duty], len(steps), n))
    c.append('};')
    h = ['/* generated by tools/sfx_tables.py - do not edit */', '#ifndef SFX_TABLES_H', '#define SFX_TABLES_H',
         '#include <stdint.h>',
         'typedef struct { uint16_t x; uint8_t env; } sfx_step_t;   /* env: NR22 with a retrigger, 0 = glide */',
         'typedef struct { uint8_t duty; uint8_t len; const sfx_step_t *steps; } sfx_prog_t;',
         'enum { ' + ', '.join('SFX_' + n.upper() for n in names) + ' };',
         'extern const sfx_prog_t sfx_progs[];', '#endif']
    root = os.path.join(os.path.dirname(__file__), '..')
    open(os.path.join(root, 'src', 'sfx_tables.c'), 'w').write('\n'.join(c) + '\n')
    open(os.path.join(root, 'include', 'sfx_tables.h'), 'w').write('\n'.join(h) + '\n')
    print('wrote src/sfx_tables.c (%s)' % ', '.join('%s %d frames' % (n, len(EFFECTS[n][1])) for n in names))

if __name__ == '__main__':
    build()
